# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Burke_edu

email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# twitter_username: username
bluesky_username: jamespburke.com
github_username: JamesPBurke
minimal_mistakes_skin: sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/

# Pagination settings
pagination:
  enabled: true
  collection: posts # collection to paginate
  per_page: 5 # number of posts per page
  permalink: '/page/:num/' # used for the permalink of the page
  title: ':title - page :num' # used for the title of the page
  limit: 0 
  sort_field: 'date' 
  sort_reverse: true 
  trail: 
    before: 2 # number of pages before the current page
    after: 2 # number of pages after the current page

timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

repository: JamesPBurke/JamesPBurke.github.io
show_excerpts: true
excerpt_separator: "<!--more-->"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "JP Burke"
  avatar : "/assets/images/bio-snap.jpg"
  bio    : "Playful educator, culinary explorer, and lifelong learner. B.Sc. Computer Science, Ph.D. Mathematics Education."
  location: "Massachusetts, USA"
  home: "/about/"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/jamespburke.com/"

logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
og_image: /assets/images/logo.png



comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.

footer:
  links:
    #- label: "Twitter"
    # icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"    
    - label: "Bluesky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/jamespburke.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JamesPBurke/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/drjpburke/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jpburke/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
